<?php

/**
 * @file
 * Contains take_a_pet.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * implements hook_form_alter()
 */
function take_a_pet_form_alter(&$form, &$form_alter, $form_id){
    $form['#attached']['library'][] = 'take_a_pet/take_a_break_form_adopter';
}

/**
 * Implements hook_help().
 */
function take_a_pet_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the take_a_pet module.
    case 'help.page.take_a_pet':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allows us to adopt a pet') . '</p>';
      return $output;

    default:
  }
}
